[package]
name = "purgery-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
purgery-core = { path = "../purgery-core" }
anyhow = "1"
camino = { version = "1", features = ["serde1"] }
walkdir = "2"
sha2 = "0.10"
toml = "1.1"
