[package]
name = "purgery-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
purgery-core = { path = "../purgery-core" }
anyhow = "1"
regex = "1"

[dev-dependencies]
tempfile = "3"
camino = { version = "1", features = ["serde1"] }
