nickname = "laptop"
state_dir = "/var/lib/purgery"

[server]
host = "example.com"

[[root]]
name = "videos"
path = "/home/user/Videos"

[[root]]
name = "configs"
path = "/home/user/my/server-configs"

[[sync]]
from = "videos/cats"
to = "univ/videos/cats"

[[sync]]
from = "configs"
to = "sys/server-configs"
delete_after_import = true

[[sync]]
from = "videos"
to = "univ/videos"
match = "**/*dog*.png"
postprocess = ["compress-image"]
delete_after_import = true
