nickname = "laptop"
state_dir = "/var/lib/purgery"

[server]
host = "example.com"

[[sync]]
name = "videos"
from = "/home/vitalik/Videos"
to = "videos"
delete_after_import = true

[[sync]]
name = "pictures"
from = "/home/vitalik/Pictures"
to = "pictures"
delete_after_import = true

[[postprocess.rules]]
match = "*.mp4"
steps = ["compress-video"]

[[postprocess.rules]]
match = "*.mov"
steps = ["compress-video"]

[[postprocess.rules]]
match = "*.mkv"
steps = ["compress-video"]

[[postprocess.rules]]
match = "*.webm"
steps = ["compress-video"]
