root = "/universe/synced"
purgery_root = "/universe/tmp/purgery"

[postprocess]

[postprocess.steps.compress-video]
kind = "subprocess"
program = "my-compress-video"
args = ["--input", "{input}"]
expected_outputs = ["{file_stem}.Z.webm"]
keep_original = true
